// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk7GuTuQOR4r2YoMm_SH-IFRxNHU7njJg',
    appId: '1:450942961159:web:d928a93dc3ee8b188d0ca2',
    messagingSenderId: '450942961159',
    projectId: 'chat-app-bb8f8',
    authDomain: 'chat-app-bb8f8.firebaseapp.com',
    storageBucket: 'chat-app-bb8f8.appspot.com',
    measurementId: 'G-XWZGQ6Q7SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFB-9Vc-Y4ytwXmVRTWKLlNw7jGGb5blY',
    appId: '1:450942961159:android:50dcd38fcd0e26758d0ca2',
    messagingSenderId: '450942961159',
    projectId: 'chat-app-bb8f8',
    storageBucket: 'chat-app-bb8f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD71f2Awod85lVBFIzYD1ByMwEPabXXC1g',
    appId: '1:450942961159:ios:4025bf13d358e72b8d0ca2',
    messagingSenderId: '450942961159',
    projectId: 'chat-app-bb8f8',
    storageBucket: 'chat-app-bb8f8.appspot.com',
    iosClientId: '450942961159-t2kna44nrlsbhqbupuljsumesnpu3jlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
